baseURL = "https://reactionair.nl/"
title   = "Reactionair.nl"

languageCode           = "nl"
DefaultContentLanguage = "nl"

googleAnalytics = "G-MM83VY2NM0"

paginate     = 10
paginatePath = "pagina"

removePathAccents = true

[taxonomies]
	auteur    = "auteurs"
	dossier   = "dossiers"
	thema     = "themas"
	geciteerd = "geciteerd"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[imaging]
	resampleFilter = "Lanczos"

[minify]
	minifyOutput = true
	[minify.tdewolff.html]
		keepWhitespace = false

[outputs]
	home = ["HTML", "JSON", "RSS"]
