baseURL = "https://reactionair.nl/"
title   = "Reactionair.nl"

languageCode           = "nl"
DefaultContentLanguage = "nl"

paginate     = 10
paginatePath = "pagina"

removePathAccents = true

enableRobotsTXT = true

ignoreErrors = ["error-output-taxonomy"]

disableHugoGeneratorInject = true

[params]
	revision = "847"

[taxonomies]
	auteur     = "auteurs"
	dossier    = "dossiers"
	thema      = "themas"
	aangehaald = "aangehaald"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[imaging]
	resampleFilter = "Lanczos"

[minify]
	minifyOutput = true
	[minify.tdewolff.html]
		keepWhitespace = false

[outputs]
	home     = ["HTML", "JSON", "RSS"]
	section  = ["RSS"]
	taxonomy = ["RSS"]
	term     = ["HTML", "RSS"]
	page     = ["HTML"]
