baseURL = "https://reactionair.nl/"
title   = "Reactionair.nl"

languageCode           = "nl"
DefaultContentLanguage = "nl"

paginate     = 10
paginatePath = "pagina"

removePathAccents   = true
enableRobotsTXT     = true
cleanDestinationDir = true

ignoreErrors = ["error-remote-getjson"]

[params]
	rev    = "964"
	api    = "https://admin.reactionair.nl"
	advert = "Reactionary Modernism"

[module]
	[[module.mounts]]
		source = 'content'
		target = 'content'
	[[module.mounts]]
		source = 'static'
		target = 'static'
	[[module.mounts]]
		source = 'layouts'
		target = 'layouts'
	[[module.mounts]]
		source = 'data'
		target = 'data'
	[[module.mounts]]
	    source = 'assets'
	    target = 'assets'
	[[module.mounts]]
		source = "layouts/shop/list.html"
		target = "layouts/_default/language.html"
	[[module.mounts]]
		source = "layouts/shop/list.html"
		target = "layouts/_default/publisher.html"
	[[module.mounts]]
		source = "layouts/shop/list.html"
		target = "layouts/_default/writer.html"

[taxonomies]
	author    = "authors"
	theme     = "theme"
	writer    = "writers"
	publisher = "publisher"
	language  = "language"

[permalinks]
	[permalinks.page]
		articles = "/artikelen/:slugorfilename/"
		shop     = "/winkel/producten/:sections[last]/:slugorfilename/"
	[permalinks.section]
		articles = "/artikelen/"
		shop     = "/winkel/producten/:sections[last]/"
	[permalinks.term]
		authors   = "/auteurs/:slug/"
		theme     = "/themas/:slug/"
		writers   = "/winkel/producten/boeken/auteurs/:slug/"
		publisher = "/winkel/producten/boeken/uitgeverijen/:slug/"
		language  = "/winkel/producten/boeken/talen/:slug/"
	[permalinks.taxonomy]
		authors   = "/auteurs/"
		theme     = "/themas/"
		writers   = "/winkel/producten/boeken/auteurs/"
		publisher = "/winkel/producten/boeken/uitgeverijen/"
		language  = "/winkel/producten/boeken/talen/"

[related]
	includeNewer = true

[[related.indices]]
	name   = "tags"
	weight = 100
[[related.indices]]
	name   = "theme"
	weight = 60
[[related.indices]]
	name   = "authors"
	weight = 20
[[related.indices]]
	name   = "date"
	weight = 20

[markup]
	[markup.goldmark]
		[markup.goldmark.parser]
			autoHeadingID = false
		[markup.goldmark.renderer]
			unsafe = true
	[markup.highlight]
		codeFences = false

[imaging]
	resampleFilter = "Lanczos"

[minify]
	minifyOutput = true
	[minify.tdewolff.html]
		keepWhitespace = false

[outputs]
	home     = ["html", "json", "rss"]
	section  = ["html", "rss"]
	taxonomy = ["html", "rss"]
	term     = ["html", "rss"]
	page     = ["html"]

[build]
	noJSConfigInAssets = true
