baseURL = "https://reactionair.nl/"
title   = "Reactionair.nl"

languageCode           = "nl"
DefaultContentLanguage = "nl"

ignoreErrors = ["error-remote-getjson"]

paginate     = 10
paginatePath = "pagina"

removePathAccents = true
enableRobotsTXT = true
disableHugoGeneratorInject = true
cleanDestinationDir = true

[params]
	revision = "855"

[taxonomies]
	author = "authors"
	file   = "files"
	theme  = "themes"
	cited  = "cited"

[permalinks]
	authors = "/auteurs/:slug/"
	files   = "/dossiers/:slug/"
	themes  = "/themas/:slug/"
	cited   = "/aangehaald/:slug/"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[imaging]
	resampleFilter = "Lanczos"

[minify]
	minifyOutput = true
	[minify.tdewolff.html]
		keepWhitespace = false

[outputs]
	home     = ["HTML", "JSON", "RSS"]
	section  = ["RSS"]
	taxonomy = ["RSS"]
	term     = ["HTML", "RSS"]
	page     = ["HTML"]
