baseURL = "https://reactionair.nl/"
title   = "Reactionair.nl"

languageCode           = "nl"
DefaultContentLanguage = "nl"

ignoreErrors = ["error-remote-getjson"]

paginate     = 10
paginatePath = "pagina"

removePathAccents = true
enableRobotsTXT = true
disableHugoGeneratorInject = true
cleanDestinationDir = true

[params]
	rev = "911"
	api = "https://admin.reactionair.nl"

[taxonomies]
	author = "authors"
	theme  = "themes"
	winkel = "winkel"

# TODO: See https://github.com/gohugoio/hugo/issues/8523
[permalinks]
	authors = "/auteurs/:slug/"
	themes  = "/themas/:slug/"

[related]
	includeNewer = true

[[related.indices]]
	name   = "tags"
	weight = 100
[[related.indices]]
	name   = "themes"
	weight = 60
[[related.indices]]
	name   = "authors"
	weight = 20
[[related.indices]]
	name   = "date"
	weight = 20

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[imaging]
	resampleFilter = "Lanczos"

[minify]
	minifyOutput = true
	[minify.tdewolff.html]
		keepWhitespace = false

[outputs]
	home     = ["HTML", "JSON", "RSS"]
	section  = ["RSS"]
	taxonomy = ["HTML", "RSS"]
	term     = ["HTML"]
	page     = ["HTML"]
