baseURL = "https://reactionair.nl/"
title   = "Reactionair.nl"

languageCode           = "nl"
DefaultContentLanguage = "nl"

paginate     = 10
paginatePath = "pagina"

removePathAccents          = true
enableRobotsTXT            = true
disableHugoGeneratorInject = true
cleanDestinationDir        = true

ignoreErrors = ["error-remote-getjson"]

[params]
	rev    = "958"
	api    = "https://admin.reactionair.nl"
	advert = "Our Way Back"

[taxonomies]
	author    = "authors"
	theme     = "themes"
	writer    = "writers"
	publisher = "publishers"
	language  = "languages"

[permalinks]
	[permalinks.page]
		articles = "/artikelen/:slugorfilename/"
		shop     = "/winkel/producten/:slugorfilename/"
	[permalinks.section]
		articles   = "/artikelen/"
		shop       = "/winkel/"
	[permalinks.term]
		authors    = "/auteurs/:slug/"
		themes     = "/themas/:slug/"
		writers    = "/winkel/auteur/:slug/"
		publishers = "/winkel/uitgeverij/:slug/"
		languages  = "/winkel/taal/:slug/"
	[permalinks.taxonomy]
		authors    = "/auteurs/"
		themes     = "/themas/"
		writers    = "/winkel/auteur/"
		publishers = "/winkel/uitgeverij/"
		languages  = "/winkel/taal/"

[related]
	includeNewer = true

[[related.indices]]
	name   = "tags"
	weight = 100
[[related.indices]]
	name   = "themes"
	weight = 60
[[related.indices]]
	name   = "authors"
	weight = 20
[[related.indices]]
	name   = "date"
	weight = 20

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[imaging]
	resampleFilter = "Lanczos"

[minify]
	minifyOutput = true
	[minify.tdewolff.html]
		keepWhitespace = false

[outputs]
	home     = ["html", "json", "rss"]
	section  = ["html", "json", "rss"]
	taxonomy = ["html", "rss"]
	term     = ["html", "rss"]
	page     = ["html"]

[build]
	noJSConfigInAssets = true
