baseURL = "https://reactionair.nl/"
title   = "Reactionair.nl"

languageCode           = "nl"
DefaultContentLanguage = "nl"

paginate     = 10
paginatePath = "pagina"

removePathAccents = true
enableRobotsTXT = true
disableHugoGeneratorInject = true
cleanDestinationDir = true

ignoreErrors = ["error-remote-getjson"]

[params]
	rev = "916"
	api = "https://admin.reactionair.nl"

[taxonomies]
	author  = "authors"
	theme   = "themes"
	shop	= "shop"

[permalinks]
	[permalinks.page]
		articles = "/artikelen/:slug/"
		shop	 = "/winkel/producten/:slug/"
	[permalinks.section]
		articles   = "/artikelen/"
		newsletter = "/nieuwsbrief/"
		shop	   = "/winkel/"
	[permalinks.term]
		authors = "/auteurs/:slug/"
		themes  = "/themas/:slug/"
	[permalinks.taxonomy]
		authors = "/auteurs/"
		themes  = "/themas/"
		shop	= "/winkel/"

[related]
	includeNewer = true

[[related.indices]]
	name   = "tags"
	weight = 100
[[related.indices]]
	name   = "themes"
	weight = 60
[[related.indices]]
	name   = "authors"
	weight = 20
[[related.indices]]
	name   = "date"
	weight = 20

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[imaging]
	resampleFilter = "Lanczos"

[minify]
	minifyOutput = true
	[minify.tdewolff.html]
		keepWhitespace = false

[outputs]
	home     = ["HTML", "JSON", "RSS"]
	section  = ["RSS"]
	taxonomy = ["HTML", "RSS"]
	term     = ["HTML"]
	page     = ["HTML"]
