backend:
  name: "git-gateway"
  branch: "main"
  identity_url: "https://reactionair.nl/.netlify/identity"
  gateway_url: "https://reactionair.nl/.netlify/git"

media_folder: ""
public_folder: ""

site_url: "https://reactionair.nl"
logo_url: "https://reactionair.nl/img/logo.svg"

locale: "nl"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "artikelen"
    label: "Artikelen"
    label_singular: "Artikel"
    folder: "content/artikelen"
    path: "{{slug}}/index"
    format: "toml-frontmatter"
    create: true
    delete: false
    fields:
      - name: "title"
        label: "Titel"
        widget: "string"
  - name: "auteurs"
    label: "Auteurs"
    label_singular: "Auteur"
    folder: "content/auteurs"
    path: "{{slug}}/_index"
    format: "toml-frontmatter"
    create: true
    delete: false
    fields:
      - name: "title"
        label: "Naam"
        widget: "string"
      - name: "profession"
        label: "Kernwoord"
        widget: "string"
      - name: "description"
        label: "Beschrijving"
        widget: "text"
      - name: "pseudonym"
        label: "Anoniem"
        widget: "boolean"
      - name: "image"
        label: "Afbeelding"
        widget: "image"
        allow_multiple: false
        choose_url: false
  - name: "dossiers"
    label: "Dossiers"
    label_singular: "Dossier"
    folder: "content/dossiers"
    path: "{{slug}}/_index"
    format: "toml-frontmatter"
    create: true
    delete: false
    fields:
      - name: "title"
        label: "Naam"
        widget: "string"
      - name: "description"
        label: "Beschrijving"
        widget: "text"
      - name: "heading"
        label: "Titel (op pagina's)"
        widget: "string"
  - name: "themas"
    label: "Themas"
    label_singular: "Thema"
    folder: "content/themas"
    path: "{{slug}}/_index"
    format: "toml-frontmatter"
    delete: false
    fields:
      - name: "title"
        label: "Naam"
        widget: "string"
      - name: "description"
        label: "Beschrijving"
        widget: "text"
      - name: "heading"
        label: "Titel (op pagina's)"
        widget: "string"
