query getArtikelenDocument($relativePath: String!) {
  getArtikelenDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...ArtikelenParts
    }
  }
}

query getArtikelenList {
  getArtikelenList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...ArtikelenParts
        }
      }
    }
  }
}
