query artikelen($relativePath: String!) {
  artikelen(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArtikelenParts
  }
}

query artikelenConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String) {
  artikelenConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
  ) {
    totalCount
    edges {
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArtikelenParts
      }
    }
  }
}

query dossiers($relativePath: String!) {
  dossiers(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DossiersParts
  }
}

query dossiersConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String) {
  dossiersConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
  ) {
    totalCount
    edges {
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DossiersParts
      }
    }
  }
}
